server:
  port: 80
spring:
  application:
    name: zull

eureka:
  instance:
    prefer-ip-address: true #优先使用ip地址注册到eureka
    lease-renewal-interval-in-seconds: 5 #服务续约间隔为5
    lease-expiration-duration-in-seconds: 10 #服务失效时间为10
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone : http://localhost:8761/eureka/,http://localhost:8762/eureka/
      defaultZone : http://106.52.187.176:8761/eureka

#如果转发路径与微服务的名称是一样的，这段配置完全不需要配置
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


zull:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  rotues:
    book: #需要转发的微服务名称
      path: /book/** #需要转发的路径
      url: http://106.52.187.176:8081/ #最终需要转发微服务的名称
    order:
      path: /order/** #需要转发的路径
      url: order #最终需要转发微服务的名称
    user:
      path: /user #需要转发的路径
      serviceId: user #最终需要转发微服务的名称