server:
  port: 80
spring:
  application:
    name: zull

eureka:
  instance:
    prefer-ip-address: true #优先使用ip地址注册到eureka
  client:
    register-with-eureka: true #消费方不是必须注册到eureka
    fetch-registry: true
    service-url:
      #defaultZone : http://localhost:8761/eureka/,http://localhost:8762/eureka/
      defaultZone : http://106.52.187.176:8761/eureka
    registry-fetch-interval-seconds: 5 #刷新注册信息的间隔时间

#如果转发路径与微服务的名称是一样的，这段配置完全不需要配置
zull:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  rotues:
    microserver-user:
      path: /book #需要转发的路径
      serviceId: book #最终需要转发微服务的名称
    microserver-movie:
      path: /order #需要转发的路径
      serviceId: order #最终需要转发微服务的名称
    microserver-pay:
      path: /user #需要转发的路径
      serviceId: user #最终需要转发微服务的名称